import tableStyles from '../styles/Table.module.css'

const Table = () => {
    // theadの最初の曜日を定義すると自動で更新されます
    const startDay = 8

    const content = [
        {
            time: 4,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: 'euro',
            thuLeague: 'SC',
            friClass: '',
            friLeague: '',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 5,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: 'euro',
            thuLeague: 'SC',
            friClass: '',
            friLeague: '',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 6,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 7,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 8,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 9,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 10,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 11,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 12,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 13,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 14,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'j',
            satLeague: 'J',
        },
        {
            time: 15,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'j',
            satLeague: 'J',
        },
        {
            time: 16,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 17,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 18,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
        {
            time: 19,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: 'j',
            thuLeague: 'J',
            friClass: 'j',
            friLeague: 'J',
            satClass: 'j',
            satLeague: 'J',
        },
        {
            time: 20,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: 'j',
            thuLeague: 'J',
            friClass: 'j',
            friLeague: 'J',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 21,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 22,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'ger',
            satLeague: 'Bundes',
        },
        {
            time: 23,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 24,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 25,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 26,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: '',
            friLeague: '',
            satClass: 'multi',
            satLeague: '',
        },
        {
            time: 27,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: 'multi',
            friLeague: '',
            satClass: 'esp',
            satLeague: 'LaLiga',
        },
        {
            time: 28,
            sunClass: '',
            monClass: '',
            tueClass: '',
            tueLeague: '',
            wedClass: '',
            wedLeague: '',
            thuClass: '',
            thuLeague: '',
            friClass: 'multi',
            friLeague: '',
            satClass: '',
            satLeague: '',
        },
    ]

    return (
        <table className={tableStyles.table}>
            <thead>
                <tr>
                    <th>時</th>
                    <td>{startDay}(日)</td>
                    <td>{startDay + 1}(月)</td>
                    <td>{startDay + 2}(火)</td>
                    <td>{startDay + 3}(水)</td>
                    <td>{startDay + 4}(木)</td>
                    <td>{startDay + 5}(金)</td>
                    <td>{startDay + 6}(土)</td>
                </tr>
            </thead>
            <tbody>
                {content.map((row) => (
                    <tr key={row.time}>
                        <th>{row.time}</th>
                        <td className={tableStyles[row.sunClass]}></td>
                        <td className={tableStyles[row.monClass]}></td>
                        <td className={tableStyles[row.tueClass]}></td>
                        <td className={tableStyles[row.wedClass]}></td>
                        <td className={tableStyles[row.thuClass]}>{row.thuLeague}</td>
                        <td className={tableStyles[row.friClass]}>{row.friLeague}</td>
                        <td className={tableStyles[row.satClass]}>{row.satLeague}</td>
                    </tr>
                ))}
            </tbody>
        </table>
    )
}

export default Table
